### ISSUE TITLE
Add classes to support pmt creation from flatbuffer structures.

### ISSUE THREAD

**Issue by jsallay** [gnuradio/pmt#8]
One of the big promises of the new pmt structure is that it should make it easier to work with well defined structures.  Ideally we should be able to create a flatbuffer object, wrap it in a pmt, and send/receive that as a message.  I think that support is kind of there in the pmtf base class, but we should make a flatbuffer object a first class citizen like map and vector.

**Comment by mormj** [comment]
Functionally, how would you expect this to look?  Could it be done modularly, out of tree so that any .fbs file could be used as long as both sides of the pmt have access to it?  Just trying to get my head around the concrete workflow

**Comment by jsallay** [comment]
That's a good question.  I was originally thinking that you would distribute the .fbs file with your block.  However, that causes an issue of multiple blocks needing to use the same file.  Off the top of my head.  I would think that we could have a folder of fbs files in each OOT module.  I would probably install all of these files to a common location and then the user could use whatever it available.

In this case, you would still have users who had to download an OOT module just to get an .fbs file.  Although this is annoying, it is can be pretty easily remedied by having a fbs package (in whatever system) for an OOT module.

**Comment by jsallay** [comment]
No longer using flatbuffers.
